### ISSUE TITLE
Disabling SCTP checksum

### ISSUE THREAD

**Issue by lgrahl** [NEAT-project/usrsctp-neat#13]
When setting `SCTP_WITH_NO_CSUM`, what does it do exactly?

- [ ] disable generating the checksum for outgoing packets
- [ ] disable verifying the checksum for incoming packets, or
- [ ] something else entirely

**Comment by tuexen** [comment]
Supporting this has been removed from the upstream version. It was used ages ago to figure out how fast SCTP implementations can be with CRC32 offload. So it is not needed anymore.

There is an API to provide your own CRC32c implementation in case of you want a zero checksum or do some assembly speedup.

**Comment by lgrahl** [comment]
Does that API allow to not verify the checksum for incoming packets but still generate it for outgoing packets? This is what I would like to do to check it's performance impact (while staying compatible).

**Comment by tuexen** [comment]
Yes, you can do that. Have a look at `programs/ekr_loop_offload.c`. However, I would not say that you are compatible when not detecting checksum errors. The zero checksum stuff I mentioned is used by someone, when he controls both sides and he signals this OOT (using SDP).

**Comment by lgrahl** [comment]
Perfect, I'll check it out.

> However, I would not say that you are compatible when not detecting checksum errors.

Granted but shouldn't checksum errors be unlikely on top of DTLS if the other peer's SCTP implementation behaves correctly?

**Comment by tuexen** [comment]
That is correct, and that is an argument why you could disable the checksum when running on top of DTLS...

**Comment by lgrahl** [comment]
That answers all my question. Cheers!
