### ISSUE TITLE
usrsctp-neat motivation

### ISSUE THREAD

**Issue by jmillan** [NEAT-project/usrsctp-neat#14]
Hi team,

I don't find any documentation regarding the usrsctp-net motivation nor about the differences between the original usrsctp project and this one.

Could you please point (or tell) me about it, and about the scenarios in which one would decide using one or the other library?

Thanks a lot.

**Comment by lgrahl** [comment]
IIRC this is just usrsctp with some patches to let it run in libuv which was needed for the neat network stack. @tuexen told me that the required changes to run usrsctp in an event loop (single threaded and the timer function being exposed) are planned to be merged back. I think they are just extremely scarce on resources. See https://github.com/sctplab/usrsctp/issues/292.

You can read more about the [NEAT project here](https://www.neat-project.org/).

**Comment by ibc** [comment]
> You can read more about the [NEAT project here](https://www.neat-project.org/).

Once you accept the expired TLS certificate of the website...

**Comment by jmillan** [comment]
Thanks for the info.

Luckily usrsctp already supports running in an event loop :-).
